# Generated by Django 4.2.30 on 2026-08-11 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Szolgáltatás neve')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('price', models.IntegerField(verbose_name='Ár (Ft)')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Időtartam (perc)')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Kép URL (vagy Helyőrző)')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Teljes név')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail cím')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefonszám')),
                ('date_time', models.DateTimeField(verbose_name='Foglalás időpontja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.service', verbose_name='Kiválasztott szolgáltatás')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
